### ISSUE TITLE
Image array returned for usage in Python-Keras for Deep Learning 

### ISSUE THREAD

**Issue by zamanashiq3** [Breakthrough/PySceneDetect#146]
**Description of Problem & Solution**
I'm working with the Video surveillance footage analysis and this pyscenedetect s excellent for context-aware changed image extractions. But there is no python interface for returning image array for me to process with other code in real-time or if there is I did not get it on the documentation. So, I propose an interface to grab this image as an image numpy array.

**Proposed Implementation:**
So, the basic scene manager should have a method for the return processed image frame in the function that I can use later in code for proper DNN based processing.

**Comment by wjs018** [comment]
This is related to #88 and there was a function added recently to do this in the `scene_manager` module [here](https://github.com/Breakthrough/PySceneDetect/blob/master/scenedetect/scene_manager.py#L243). If I understand the use of this function correctly, you would need to have already analyzed a video and gotten the complete scene list. Then, feed that scene list and the `video_manager` into this function and it will generate the images as files (jpg, webp, or png) using `cv2.imwrite`.

If you want those images as numpy arrays, you can then read them in using whatever method you would normally use for image data in your preferred ML library. For Keras and Tensorflow, it would be using the `load_img` function ([docs](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/load_img)).

To bypass the step of writing the images to file would require manually grabbing frames from the video given the timecodes of the detected scenes. You could replicate the behavior of the [above function](https://github.com/Breakthrough/PySceneDetect/blob/ed69e21ffa5881ef63652644d864248e5872cb14/scenedetect/scene_manager.py#L328) by grabbing the frames through seeking in the `video_manager` and instead of saving them to file, just saving them as a numpy array (OpenCV uses numpy arrays internally already). Specifically, the image numpy array that you would want is named `frame_im` in [this line](https://github.com/Breakthrough/PySceneDetect/blob/ed69e21ffa5881ef63652644d864248e5872cb14/scenedetect/scene_manager.py#L332).

**Comment by zamanashiq3** [comment]
This is exactly what I wanted. Thank you for the detailed answer. I think i will close this issue now.

**Comment by Wunaiq** [comment]
> This is related to #88 and there was a function added recently to do this in the `scene_manager` module [here](https://github.com/Breakthrough/PySceneDetect/blob/master/scenedetect/scene_manager.py#L243). If I understand the use of this function correctly, you would need to have already analyzed a video and gotten the complete scene list. Then, feed that scene list and the `video_manager` into this function and it will generate the images as files (jpg, webp, or png) using `cv2.imwrite`.
> 
> If you want those images as numpy arrays, you can then read them in using whatever method you would normally use for image data in your preferred ML library. For Keras and Tensorflow, it would be using the `load_img` function ([docs](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/load_img)).
> 
> To bypass the step of writing the images to file would require manually grabbing frames from the video given the timecodes of the detected scenes. You could replicate the behavior of the [above function](https://github.com/Breakthrough/PySceneDetect/blob/ed69e21ffa5881ef63652644d864248e5872cb14/scenedetect/scene_manager.py#L328) by grabbing the frames through seeking in the `video_manager` and instead of saving them to file, just saving them as a numpy array (OpenCV uses numpy arrays internally already). Specifically, the image numpy array that you would want is named `frame_im` in [this line](https://github.com/Breakthrough/PySceneDetect/blob/ed69e21ffa5881ef63652644d864248e5872cb14/scenedetect/scene_manager.py#L332).

Your solution is definitely worked，but if there could be an API for returning frame numpy arraies, the object scene_manager will be more complete, cause this API will be very useful to Deep Learning about videos.
