### ISSUE TITLE
Documentation Improvement - `$VIDEO_NAME` macro does not work if not escaped correctly

### ISSUE THREAD

**Issue by wjs018** [Breakthrough/PySceneDetect#149]
**Bug/Issue Description:**

As discussed in #145, setting the `.csv` file output name from the `list-scenes` command is not working with the `$VIDEO_NAME` macro. Instead, there is no output where the video name should be. This is also true when I tested it using the `export-html` command.

**Required Information:**
Provide the following information to assist with reporting the bug:
1. Provide a full copy of the command line options you are using, for example:

Example using `list-scenes`:
`scenedetect --input goldeneye.mp4 detect-content -t 30 list-scenes -f "$VIDEO_NAME-Stats-30.csv"`

Example using `export-html`:
`scenedetect --input goldeneye.mp4 detect-content -t 30 list-scenes -f "$VIDEO_NAME-Stats-30.csv" save-images export-html -f "$VIDEO_NAME-html-test.html" `

2. Add `-v debug -l BUG_REPORT.txt` to the beginning of the command, then re-run PySceneDetect and **attach the generated `BUG_REPORT.txt` file**.

`list-scenes` command from above:
[BUG_REPORT.txt](https://github.com/Breakthrough/PySceneDetect/files/4120829/BUG_REPORT.txt)

`export-html` command from above:
[BUG_REPORT.txt](https://github.com/Breakthrough/PySceneDetect/files/4120897/BUG_REPORT.txt)

**Expected Behavior:**

I expected the csv file output to be `goldeneye-Stats-30.csv` or `goldeneye.mp4-Stats-30.csv` depending on what the intended behavior of stripping the file extension should be. However, the resulting csv file has the filename `-Stats-30.csv`. Other than the `$VIDEO_NAME` macro, the `-f` flag seems to be working as intended.

**Computing Environment:**
 - OS: Ubuntu 18.04
 - Python Version: 3.8.1
 - OpenCV Version: 4.1.2

**Additional Information:**

I installed the latest version of scenedetect from the master branch on github. It is listed as version v0.5.2-dev.

**Edit** Also verified this bug exists with the `export-html` command.

**Comment by wjs018** [comment]
I was able to figure out the problem I had with this. The fix is really simple, just enclose the `-f` parameter with single quotes to make sure bash doesn't ready in `$VIDEO_NAME` as a bash variable. I had remembered my bash escape characters incorrectly.

For completeness, the command from above should be:
`scenedetect --input goldeneye.mp4 detect-content -t 30 list-scenes -f '$VIDEO_NAME-Stats-30.csv'`

I am closing this issue, but the documentation might be improved to reflect this issue in the future.

**Comment by Breakthrough** [comment]
Hey @wjs018;

That's a good point - I'll reopen this, because the documentation SHOULD reflect this.  If you ran into this issue, other users definitely will, and I can see that as being a gotcha that should be documented more clearly.

Reopening this so that it gets addressed - renaming the title to better reflect that, feel free to modify as required.

Thanks!

**Comment by Breakthrough** [comment]
Another option just came to my mind - what if we allow an additional character to be used, or different format for the macros (e.g. `{VIDEO_NAME}` instead of `$VIDEO_NAME`)?  I could likely implement such a change in a non breaking manner, but would love to hear some feedback first before deciding on anything.

In the meantime, I'll add a note to the command-line interface itself indicating that users may need to escape the template with single quotes as you mentioned.

**Comment by Breakthrough** [comment]
Resolved in v0.5.4.
