### ISSUE TITLE
runtime error with TypeError

### ISSUE THREAD

**Issue by gitcomo** [Breakthrough/PySceneDetect#16]
Hello,

I'm trying to test pySceneDetect with Python 2.7.12, numpy 1.11.1, scipy 0.17.1 and openCV 2.4.13 on Windows 10 64bit.
All seemed good but I got error when trying to run PySceneDetect on command line, that was:

C:\Works>scenedetect -i goldeneye.mp4
[PySceneDetect] Detecting scenes (threshold mode)...
[PySceneDetect] FATAL ERROR - could not open video goldeneye.mp4.
Traceback (most recent call last):
  File "C:\2ndPrograms\Python27\Scripts\scenedetect-script.py", line 9, in <module>
    load_entry_point('PySceneDetect==0.3.4', 'console_scripts', 'scenedetect')()
  File "c:\2ndprograms\python27\lib\site-packages\scenedetect__init__.py", line 346, in main
    timecode_list = timecode_list
TypeError: 'int' object is not iterable

What is my fault? I think your code worked correctly but someone said TypeError needed to be fixed like in using List according to googling.
Sorry for writing this asking in Issue raising page.
Thank you.

**Comment by Breakthrough** [comment]
Hi @gitcomo;

No problem, this is indeed the proper place to bring up such an issue.  Thank you for providing full details/output, much appreciated.  You can ignore the `TypeError` exception, this is a side-effect of the video not being loaded, and will be fixed in the following release. 

The problem here is the video could not be loaded.  In this case, it appears the file does exist, and if you can play it locally, I would make sure you have OpenCV installed properly.  Specifically, the `opencv_ffmpegXX.dll` (`opencv_ffmpegXX_64.dll` for x64) needs to exist in your `$PATH` environment variable, or at least the current working directory.

To check if this is the case, run a Python prompt where `goldeneye.mp4` is, and type:

    import cv2
    cap = cv2.VideoCapture('goldeneye.mp4')
    cap.isOpened()

If you don't get `True`, [download the OpenCV release](http://opencv.org/downloads.html) matching your Python module, place the DLL file where the goldeneye.mp4 file is, and try running the above again.

Let me know when you've tried this and if it solves the issue (otherwise I'll certainly continue looking into it).  I'll try to detect this behaviour in the future and display a more helpful error message.
 - Breakthrough

**Comment by Breakthrough** [comment]
@gitcomo any luck?

**Comment by sheimend** [comment]
I'm having the very same issue. I've verified that the path to the opencv_ffmpeg310_64.dll is in my PATH variable, and when I run the test steps you have above, cap.isOpened() returns False.

When I tried putting the DLL in the same directory as my MP4 file, I still get the error referring to line 346.

Any help you can provide is greatly appreciated! Also, I'm very new to Python, so it's entirely possibly my ignorance that's causing the issue.

**Comment by Breakthrough** [comment]
@sheimend are you running a 32-bit or 64-bit Python interpreter?  If you're unsure, run the following in a Python prompt, which will return 4 on 32-bit, and 8 on 64-bit:

    import ctypes
    print ctypes.sizeof(ctypes.c_voidp)

Also, may I ask how you installed the OpenCV module?  Did you install it via `pip` or get it from the OpenCV website?  I doubt you've done anything wrong, although do double-check you're using the proper DLL file.

I just double checked and indeed the test code with `cap` only fails when I'm missing the ffmpeg DLL file in my working directory (tested with 3.1.0 using the same DLL file), so any other information that might help replicate the error would be appreciated.

**Comment by sheimend** [comment]
Thank you so much for the quick reply! It turned out to be an environment
issue, but is now resolved. What a great piece of software! Made me look
like a hero today :-)

One feature request: id love an HTML output option that creates a table,
like the CSV, but that also includes the frame grab thumbnails. I was able
to recreate this structure in Excel by writing a macro to insert the
pictures in each row, but an HTML table might make the format more
accessible for folks less familiar with Excel scripting.

Thanks again!
-Scott

**Comment by Breakthrough** [comment]
Hey  @sheimend / @gitcomo, I've made a new release including a bug-fix for the exception that was being thrown.

I also managed to use PyInstaller to generate a portable executable that includes all the required dependencies.  If you want to try that out, download [the `PySceneDetect-0.3.5-win64.zip` file](https://github.com/Breakthrough/PySceneDetect/releases/download/v0.3.5/PySceneDetect-0.3.5-win64.zip) from [the Releases page](https://github.com/Breakthrough/PySceneDetect/releases/).

Once you extract the files, you should be able to run the `scenedetect.exe` file without any problems!

**Comment by Breakthrough** [comment]
@sheimend:

Admittedly I'm not as familiar with (X)HTML/CSS as I'd like to be, but I have to say this is a *brilliant* idea.  If you'd like, you can [create/open a new issue](https://github.com/Breakthrough/PySceneDetect/issues/new) for the feature request (and then can separate the two discussions/issues if any more questions arise), and yes I can immediately see how useful such a thing would be, so again, great idea :smile: 

Glad you managed to get everything working, and thanks for keeping me updated!

**Comment by mahdisr85** [comment]
I am having the same issue on OS X El Capitan. 
I have opencv3.0 that I have installed using pip and it works properly. My guess is some sort of package conflicts in versions. Do you have any ideas?

```python /usr/local/bin/scenedetect --input input.mp4 --output scenes.csv
[PySceneDetect] Detecting scenes (threshold mode)...
WARNING: Couldn't read movie file input.mp4
[PySceneDetect] FATAL ERROR - could not open video input.mp4.
Traceback (most recent call last):
  File "/usr/local/bin/scenedetect", line 8, in <module>
    sys.exit(load_entry_point('PySceneDetect==0.3.4', 'console_scripts', 'scenedetect')())
  File "/Library/Python/2.7/site-packages/scenedetect/__init__.py", line 346, in main
    timecode_list = timecode_list
TypeError: 'int' object is not iterable```

**Comment by Breakthrough** [comment]
@mahdisr85 that's interesting, when you run the following in your working directory from a Python prompt, what do you get?

    import cv2
    cv2.__version__
    cap = cv2.VideoCapture('input.mp4')
    cap.isOpened()

Also, you might want to try compiling/installing OpenCV from source on OSX, as the packages on `pip` may be compiled with certain options/dependencies not present on your system (on Linux I've always found compiling/installing OpenCV from source presented the least amount of issues).

**Comment by Breakthrough** [comment]
@mahdisr85 Any update?

**Comment by mahdisr85** [comment]
I installed it using the source and it works now. My guess it had to do something with the fact that I use homebrew Python and the scripts were explicitly running on system Python. Thanks.

**Comment by GregS2** [comment]
Same problem here, and copying the aforementioned DLL to my working directory did fix the problem. I had used the procedure [here](http://breakthrough.github.io/Installing-OpenCV/) to install OpenCV. How is the DLL supposed to be installed, when that procedure simply says to copy the OpenCV module to the Python directory?

**Comment by Breakthrough** [comment]
@GregS2 I apologize, I should update that guide.  That only covers installing the OpenCV Python module, not OpenCV itself.  The .DLL files that come with the corresponding OpenCV release must be placed somewhere in your system's %PATH% to "install" the OpenCV DLL files (shared libraries) onto your computer.

**Comment by Breakthrough** [comment]
To solve dependency-related runtime errors for Windows users, new versions of PySceneDetect are distributed with a complete set of binaries, both as a .MSI installer, and in portable .ZIP format (64-bit only).
