### ISSUE TITLE
Feature request: HTML export

### ISSUE THREAD

**Issue by sheimend** [Breakthrough/PySceneDetect#17]
I'd love a feature, similar to the existing CSV export, that saved each detected scene into a formatted HTML document that included the thumbnail frames that get saved out on scene detection change. 

The HTML doc would contain a table with the same headers as the CSV currently has. However, there'd be a "Frame Image" column that includes one or more of the JPG frame grabs. Each scene would be represented by a row. 

For folks who want to do further analysis (in Excel, for instance), it'd much easier to import an HTML table into Excel than it is to add images to a table without them - although that's also possible with an Excel macro.

You can construct the HTML file in the same section of code that currently builds the CSV, either using an HTML builder (I'm sure Python supports one?) or even just by hand by writing out the table markup.

Anyhow, super awesome piece of code you've got. Totally made my day yesterday!

**Comment by Breakthrough** [comment]
Hey @sheimend;

I recently added built-in support for splitting videos to PySceneDetect, and will be adding this to the list of features to tackle next... Feel I should mention this because in v0.4 and above the command line option `-o` defaults to the *video* output now, not the scene list output (the option is now `-co`, or `--csv-output`).

There's two approaches to implementing this that are reasonable.  The first is changing the output option from `--csv-output` to `--scene-list-output` (`-so`), and making the output format selectable (and easy to customize).  The second would be to simply add another flag `-ho` (`--html-output`) that outputs an HTML file, as well as any images to an `img/` folder (if it exists).

I'm leaning towards the latter implementation, but am open to any suggestions you might have.

**Comment by Breakthrough** [comment]
Hi @qazqwezxc;

There hasn't been any progress on this actually, feel free to have a go at it!

I'm thinking there should be a new command like `export-html` or something, which should imply `save-images`, and functions roughly the same way (saves an HTML file with the same name as the video in the working directory, and an override is allowed like `export-html --file "some_dir/my_html_file.html"`).

Also the command should reflect the global output directory flag (`-o`).

Thoughts?  Thanks for your interest.

**Comment by wjs018** [comment]
@Breakthrough 

I know there is a big refactor going on for v0.6, but I took a crack at this and I have it working in my test environment [(code here)](https://github.com/wjs018/PySceneDetect/tree/html-export). I added the `export-html` command with a couple options. It uses the `simpletable` repo from [here](https://github.com/matheusportela/simpletable) that I forked and added image support to [here](https://github.com/wjs018/simpletable/tree/add_images).

For the `export-html` command, I added options as follows:
* `--filename / -f`: This specifies the name of the resulting html file
* `--no-images`: This flag just outputs the table without the images, allows for use without the `save-images` command
* `--image-width / -w`: Optionally specify the width in pixels of the images in the table
* `--image-height / -h`: Optionally specify the height in pixels of the images in the table

Unless the `--no-images` flag is set, then the `export-html` command must come after the `save-images` command. I have never worked with click before, and I wasn't sure how to make commands imply one another. Also, because of how filepaths work in html, I just set the output html file to be saved in the same directory as the saved images (if `save-images` is used) or the global output directory otherwise.

An example command would look something like this:
`scenedetect --input goldeneye.mp4 --output output_folder detect-content save-images export-html -w 200`

**Comment by Breakthrough** [comment]
@wjs018 that is awesome! Was that simpletable thing public domain, or is there a license associated with it?  I want to clear that part up before accepting that particular part of the code into the repo (also is it available on pip?  guessing not as you included the source code...)

I had a look through your fork though, and everything looks good at a first glance - very pleased with the way you approached the problem.  Please feel free to submit a pull request if you would like, I would be happy to review the code and accept it into PySceneDetect for the next release.

I think including the --no-images flag is fine for now, so long as an error can be reported to the user it's okay to force save-images to come before export-html for now (I'll see if there's a way to accomplish one command imply another, as far as I'm aware though there isn't, so the best you can do is report an error afterwards).

Thank you so much!

**Comment by wjs018** [comment]
@Breakthrough It isn't available on pypi, but it is under the [MIT license](https://github.com/matheusportela/simpletable/blob/master/LICENSE). As for one command invoking other commands, from what I can tell, this is possible in click using `context.invoke` and/or `context.forward` [(docs)](https://click.palletsprojects.com/en/7.x/advanced/#invoking-other-commands), but I haven't really looked into it too much.

I have submitted the pull request in #104 for review.

**Comment by Breakthrough** [comment]
@wjs018 merged - thank you so much for your contribution, very pleased with the quality of your code as well.

Will be leaving this issue open until I tackle a few of the outstanding comments I brought up in review, as well as updating the documentation for this feature (thank you for well documenting your code, it makes that part much easier for me!).  I also need to make a LICENSE file for the included dependency before closing this issue (thanks for providing the link - sorry I didn't see your link before in the review - feel free to ignore that comment or reference your comment above),

**Comment by Breakthrough** [comment]
Finalized and cleaned up in 6c4c8d491f7950a5ef91a0351c9d6acde0282500.

**Comment by msililia** [comment]
`Cool `
