### ISSUE TITLE
How to determine optimum threshold?

### ISSUE THREAD

**Issue by ivrschool** [Breakthrough/PySceneDetect#187]
Thank you for the great work. I am new to this and I have got a question to ask on how to determine an optimum threshold?

From the official documents (link: [https://pyscenedetect.readthedocs.io/en/latest/examples/usage-example/] ):
**Section: Finding Optimal Threshold/Sensitivity Value**
It says, "We can determine the proper threshold in this case by generating a statistics file (with the -s / --stats option) for the video goldeneye.mp4, and **looking at the behaviour of the values** where we expect the scene break/cut to occur in scene 17."

I am not able to understand how come the optimum value '27' was derived? What do you mean by '**looking at the behaviour of the values**'? 

Please help me understand how to read the --stats.

Thank you and I am hoping for the positive reply.

**Comment by Breakthrough** [comment]
Sorry for the delay in a response.  By looking at the values, I plotted them over time to get something like this:
https://github.com/Breakthrough/PySceneDetect/blob/master/docs/img/params.png

If you run that test video and plot the results using a statsfile (e.g. `content_val` over each `frame`), then draw a line at y = 27 and you'll see what I mean.  I agree though the documentation could definitely be improved there, so I'll make this as an improvement and keep it open for now.  The next version of PySceneDetect will also include a newer detector which might reduce false positives, so your feedback is welcome when it is released.

**Comment by Tetsujinfr** [comment]
Maybe a stupid question but I got the following error while trying to get the stats outputs:
`Error: No such option: --stats`

How to you get the stats file out?

**Comment by Breakthrough** [comment]
@Tetsujinfr can you share the full command/output?  Thanks.

**Comment by charlotteguo** [comment]
Hi @Breakthrough  - thanks for the very interesting and interdisciplinary work! 
Same as @ivrschool i too have problems determining the optimum threshold. 

Writing specifically in response to your reply to the original issue, with a general Q as I'm new to this as well. 

**Reading and plotting stats:** 
1. Is your plot done withe the python API? For now I'm using command line interface with my own videos (>2GB) locally. would you recommend python/notebooks for easier plotting and interpreting charts? 
2. Can you give an example code you used for the plot? 
3. Interpreting plot labels
https://github.com/Breakthrough/PySceneDetect/blob/master/docs/img/params.png 
Can you explain how plotting mean pixel intensity against frame number helps determining threshold? Also i noticed the orange solid line is at y (`content-val`?) = 17 rather than 27; and not sure why that matches the threshold value. Shouldn't 17 be the scene number in this case? 

**General Q related to the official documentation** 
''' 
**Section: Quickstart-Usage Example**
"Note that this is _almost perfect_ - however, one of the scene cuts/breaks in scene 17 was not detected (yielding a total of 21 scenes) ... "
"... We can determine the proper threshold in this case by generating a statistics file (with the -s / --stats option) for the video goldeneye.mp4, and looking at the behaviour of the values where we expect the scene break/cut to occur in scene 17"
''' 
Q:  in command line when i run 
`scenedetect --input myownvideo.mp4 detect-content list-scenes save-images `
the generated .csv file doesn't contain thumbnails of start and end of each scene. I suspect the thumbnails are used for eyeballing where a false negative/positive might occur (given the above first quote of documentation), hence I would appreciate help in solving this problem. 

Apologies for my absurd confusion. Any pointers are helpful!

**Comment by Breakthrough** [comment]
Hey @charlotteguo;

You need to include a statsfile with the `-s/--stats` argument, e.g.:

    scenedetect --input myownvideo.mp4 --stats statsfile.csv detect-content list-scenes save-images 

This will generate a set of metrics calculated on every frame in `statsfile.csv` (specifically the `content_val` column).  I did not create the plot using Python, I just did it manually, but it should be relatively straight forward to load the resulting CSV and plot the values.  There is no API support for this, but we can consider it for a future release.

When using `detect-content`, the corresponding metric column to look at is `content_val`.  The resulting values should increase during a scene transition.

> Interpreting plot labels
> https://github.com/Breakthrough/PySceneDetect/blob/master/docs/img/params.png
> Can you explain how plotting mean pixel intensity against frame number helps determining threshold? Also i noticed the orange solid line is at y (content-val?) = 17 rather than 27; and not sure why that matches the threshold value. Shouldn't 17 be the scene number in this case?

That diagram should definitely be updated - that is specifically for `detect-threshold` and was run on a completely separate test video (the values are the results of `delta_rgb` column in a statsfile, not `content_val` as you probably want).  To your point, we should probably include a diagram of the `content_val` values for that particular video in that example.

To explain that diagram, for detect-threshold, we want to find areas where `delta_rgb` falls below some threshold.  For detect-content, we instead want to find areas where `content_val` rapidly increases.  If you run the command above on that same video but output a statsfile, and plot `content_val`, you will see where there was one missed scene transition.  Also note that for most use cases, a value of 27 is likely better, and will be the new default in a future release (see #246 for details).

Hope this helps, and your confusion is understandable - the documentation definitely does need some improvement.  I hope to include more comprehensive diagrams for the v1.0 release, but in the meantime, feel free to let me know if you have any other questions or suggestions!

**Comment by Breakthrough** [comment]
For completeness, here's what the output looks like when you plot `content_val` for the goldeneye.mp4 test video from that page:

![content_val](https://user-images.githubusercontent.com/125316/149599689-693ede1e-28b7-4ca0-bda0-a3373423db9f.png)

I created this graph by loading the statsfile CSV into Google Sheets and plotting the `content_val` column.  Where the values spike is where scene transitions are.  You can see that right around frame 1600, there is a spike but it is smaller than the default of 30.  I manually looked at the values at that point and found it was 27.05, so set the threshold to 27 to make sure it was counted as a scene cut.

The default value of 30 was just a guess by me at a reasonable value - it has never been tweaked since the original release many years ago.  As per #246, a recent benchmark on a more comprehensive set of test videos yielded an optimal value of 27 (just a coincidence that it aligns with the 27 particular to goldeneye.mp4).  There are still some videos where the value may have to be tweaked by the process above (plotting `content_val` and finding the correct threshold value manually), but I hope this will be far less of an issue when the default is changed to 27.

**Comment by charlotteguo** [comment]
Hey @Breakthrough 

Thank you for the careful replies. I've now created my own plot and started to see why threshold =27 is a good default value.
On a side note, the algorithm doesn't necessary detect scene changes (which would involve semantic meaning of the plot), though rather shot changes and cuts. This paper includes a detailed summary https://journals.sagepub.com/doi/10.1177/1550147719845277 

Though since the cinemetrics [shot length detection software](http://www.cinemetrics.lv/cinemetrics.php) has been down, your work provides an extremely helpful alternative to researchers quantifying film. Thanks!

**Comment by Breakthrough** [comment]
> On a side note, the algorithm doesn't necessary detect scene changes (which would involve semantic meaning of the plot)

Indeed, and unfortunately I have used those two terms interchangeably at times for this project which has caused some confusion.  I chose the name PySceneDetect mainly to not conflict with other existing projects.  Thanks for the link though, I should also probably include a diagram similar to the one there that denotes the difference between frames/shots/scenes/video and emphasize what PySceneDetect's purpose is (which is really a framework/application for performing shot detection).

Cinemetrics definitely was an inspiring factor for this project, so I'm glad you're finding it useful!  Feel free to reach out anytime if you have any suggestions for how the project can be improved :)

**Comment by Breakthrough** [comment]
Hey all;

I've updated the usage example to include all the information learned from this discussion:
http://scenedetect.com/en/v0.6/examples/usage-example/

These changes won't be live until v0.6 is released, so there's still time to update/change things if anything is unclear.  You can see a preview of the new v0.6 docs at:

 - Site: https://scenedetect.com/en/v0.6/
 - Docs: https://manual.scenedetect.com/en/v0.6/

Any feedback on these changes is most welcome 😄
