### ISSUE TITLE
Images generated with wrong aspect ratio

### ISSUE THREAD

**Issue by JeffJassky** [Breakthrough/PySceneDetect#195]
**Bug/Issue:**
Generated images are visually distorted if input video has a non-1.0 [Pixel Aspect Ratio (PAR)](https://en.wikipedia.org/wiki/Pixel_aspect_ratio).

**Expected Result:**
Images generated should prioritize the display aspect ratio, not the pixel aspect ratio.

In this case, output images should have been 1024 x 576 instead of 704 × 576.

**ORIGINAL VIDEO:**
Pixel Aspect Ratio: 1.455
Display Aspect Ratio: 1.778
https://user-images.githubusercontent.com/713383/103543205-23439c00-4e6c-11eb-86c2-3f838e48d5fd.mp4

**OUTPUT IMAGE:**
Desired resolution: 1024 x 576
Actual resolution: 704 × 576
![Shot-003-02](https://user-images.githubusercontent.com/713383/103543241-32c2e500-4e6c-11eb-99a2-b57be88da101.jpg)

**Comment by Breakthrough** [comment]
Hi @JeffJassky;

This should be possible.  Looks like support for this was added in OpenCV v3.4.1, so just need to make sure it gracefully supports older versions where you cannot obtain the aspect ratio through the OpenCV API.  I'll also likely need to add a flag to the `save-images` command so you can set the resizing filter (default will be bilinear/bicubic most likely).

Plan is to have this completed for the next release (v0.5.5).  Thanks for the report!

**Comment by Breakthrough** [comment]
Resolved in v0.5.5 branch.  Still need to test on OpenCV 2.  Cubic interpolation is used.

**Comment by Breakthrough** [comment]
Untested on OpenCV2, since that's now unsupported anyways.  Tested locally, and works great so far.  I'll just leave it using cubic interpolation hard-coded for now to avoid too many CLI parameters the user needs to think about (so it'll "just work" now in this case).  In the future, if required, I can expose the interpolation method to be overridden if you find it's not sufficient.  If that's the case, you can feel free to open a new feature request at that time.

Tested locally on my end and works great, will be included in next release.  Thanks again for the report & test material!!
