### ISSUE TITLE
How to catch errors using split_video functions?

### ISSUE THREAD

**Issue by AdrienLF** [Breakthrough/PySceneDetect#209]
Hi,
I'm trying to use CUDA with video_splitter.split_video_ffmpeg. It works well for most videos, however some codecs don't play well with this. So I try to catch it with an error, like so:

```
try:
    video_splitter.split_video_ffmpeg([video], scene_list, str(final_destination) + os.sep + video_name + " " + -$SCENE_NUMBER" + PurePath(video).suffix, video, arg_override="-c:v h264_nvenc", suppress_output=True, hide_progress=False)
except Exception as e:
    print(e)
    video_splitter.split_video_ffmpeg([video], scene_list, str(final_destination) + os.sep + video_name + " " + "-$SCENE_NUMBER" + PurePath(video).suffix, video, suppress_output=True, hide_progress=False)
```

It does display the error however, it doesn't register as one, and therefore doesn't trigger the exception. Is there a way to trigger it? I'm not great with exception handling in python. 

Thank you!

**Comment by Breakthrough** [comment]
Hey @AdrienLF;

Errors aren't really handled that gracefully right now with those functions, since they invoke `ffmpeg` via `subprocess.call()`, which requires examining the return value or the string output obtained via the command.

Right now the split video functions don't return anything, but it should be pretty easy to modify it to return the error code / return value from invoking `ffmpeg` (right now it just calls a logging statement at the bottom of video_splitter.py).

Does this help?

**Comment by Breakthrough** [comment]
Could you also provide an example of the output you get for both cases?  Are there any samples you can share?

**Comment by AdrienLF** [comment]
The error I get is when I try to process PRORES with h264_nvenc.

`  0%|          | 0/1386 [00:00<?, ?frame/s]root             INFO     Average processing speed 2684.29 frames/sec.
root             ERROR    Error splitting video (ffmpeg returned 1).`

It then continues with the code without raising an exception. I would prefer that it tries again without the arg override (which works correctly).

I'll try to modify the function to return ret_val, and I think in general it would be nice to be able to catch exceptions when PySceneDetect is used in a larger app.

Thanks!

**Comment by AdrienLF** [comment]
Here's how I solved it, after modifying the function to return ret_val

```
ret_val = split_video_ffmpeg([video], scene_list, str(final_destination) + os.sep + video_name + " " + "-$SCENE_NUMBER" + PurePath(video).suffix, video, arg_override="-c:v h264_nvenc", suppress_output=True, hide_progress=False)
print(ret_val)
if ret_val ==1:
	print("Retrying splitting video")
	split_video_ffmpeg([video], scene_list, str(final_destination) + os.sep + video_name + " " + "-$SCENE_NUMBER" + PurePath(video).suffix, video, suppress_output=True, hide_progress=False)
```

Interestingly it prints before displaying the error, but it works in the end:

```
1
Retrying splitting video
root             ERROR    Error splitting video (ffmpeg returned 1).
root             INFO     Splitting input video using ffmpeg, output path template:
 ...Montage part1 PRORES -$SCENE_NUMBER.mov
```

**Comment by Breakthrough** [comment]
These functions definitely could use some API work.  I'll mark this as an improvement, and set it so that the split_video functions return the last exit code rather than nothing.

Note that the logger defaults to `stderr` right now (so the output you show is definitely possible), but as part of #205 it will likely be changed to `stdout` for info/debug statements.  After #205, those functions also won't display any output

**Comment by Breakthrough** [comment]
Completed in v0.5.6 branch.
