### ISSUE TITLE
How to specify force-fps

### ISSUE THREAD

**Issue by rajagopal067** [Breakthrough/PySceneDetect#21]
I want to use scenedetect to find scenes in my video and when I run the command
`scenedetect -i video1.mp4 -o scenes_list.csv -d content -si -t 5`

This is the output I get
_[PySceneDetect] Detecting scenes (content mode)...
[PySceneDetect] Parsing video dromebox-2016_09_15-00-00-00.mp4...
[PySceneDetect] Video Resolution / Framerate: 1280 x 720 / 1.325 FPS
Verify that the above parameters are correct (especially framerate, use --force-fps to correct if required).
[PySceneDetect] Processing complete, found 0 scenes in video.
[PySceneDetect] Processed 0 frames in 0.5 secs (avg. 0.0 FPS)._

Actual FPS is 30. It's taking the wrong value. How do I correct this ?

**Comment by Breakthrough** [comment]
Hello @rajagopal067;

You can manually specify a framerate of 30 by adding `--force-fps 30` to the end of your command:

    scenedetect -i video1.mp4 -o scenes_list.csv -d content -si -t 5 --force-fps 30

--------

That being said, it appears no frames were processed even at the incorrect framerate.  If this issue persists,  for the video to be decoded by libffmpeg, you may need to add the video into a new container (I'd recommend try using mkvtoolnix), or re-encode the file.

**Comment by Breakthrough** [comment]
Noted that this option does not show up when calling `scenedetect --help`.

**Comment by Juanbuhler** [comment]
I have a video file that is detected as 0fps. WHen I try to use --force-fps, I get this:

scenedetect: error: unrecognized arguments: --force-fps 25

Moreover, I don't see a '--force-fps' option in the code, anywhere. Seems like the only mention of force-fps is in that error message.

What am I missing?

**Comment by Breakthrough** [comment]
My apologies, I had a look through the codebase and it seems that the `--force-fps` option was not implemented correctly.  This will be addressed as soon as possible, and will be fixed in the next release of PySceneDetect.

In the meantime, you can try muxing the file using mkvtoolnix into a .mkv container.  I'll let you know as soon as the bug has been fixed, thank you for the report @Juanbuhler.

**Comment by garethfoote** [comment]
Hi @Breakthrough 

I'm experiencing this problem with a few different mp4s. I've tried using ffmpeg to convert the container to MKV and OGV (w/theora) but the problem persists.

Is there a workaround for this other than converting the files?

Best,
Gareth

**Comment by squadjot** [comment]
same

**Comment by Breakthrough** [comment]
Hello all;

This has been fixed in the latest beta version (v0.5-beta), and will be included with the release of v0.5.  It should be out sometime this month, but in the meantime, feel free to start using the beta.

The option in v0.5 is now `-f/--framerate`, for example:

    scenedetect -i some-video -f 29.97 detect-content list-scenes

Thank you all for your help, feedback, patience, and suggestions in regards to making PySceneDetect even better - it means a lot to me, and I truly do appreciate everyone's contributions back to the project!! 👍
