### ISSUE TITLE
How to use the split_video_ffmpeg method for the third audio track?

### ISSUE THREAD

**Issue by yujimori1967github** [Breakthrough/PySceneDetect#271]
I want to split a file in Video OBject file format into multiple files using the split_video_ffmpeg method. There are three audio tracks in the Video OBject file format, but when you actually divide them, only the first one is the target.

The question is, is there a way to split the third part of the audio track as audio?

**Comment by Breakthrough** [comment]
Found [this answer on StackExchange](https://video.stackexchange.com/a/33343) which implies you need to set `-map 0`.  Try adding it to the `arg_override` parameter, e.g.:

    split_video_ffmpeg(
        "video.mp4",
        scene_list,
        arg_override='-map 0 -c:v libx264 -preset fast -crf 21 -c:a aac',
    )

If that works out successfully, I'll look into adding that flag to the default in the next release.  Supplying `-map 0` will select all tracks (including video/audio/subtitles) which is probably what most people will want for a default.

If you only want the third audio track, instead of `-map 0`, specify `-map 0:a:2`.  See [the ffmpeg docs](https://trac.ffmpeg.org/wiki/Map) for a full description of the `-map` argument.

Can you let me know if that works out well for you, and if you think `-map 0` is a good default?  Thanks!

**Comment by Breakthrough** [comment]
I've verified that this seems to work acceptably for a variety of different inputs, so this is likely a reasonable default.  Subtitle tracks still won't work with this, but they're ignored as-is so this change won't affect that either (`-sn` is defined for all ffmpeg commands by default).

**Comment by Breakthrough** [comment]
Added `-map 0` to default `ffmpeg` args, will be included in v0.6.1 release.
