### ISSUE TITLE
Add mention about SignPath Foundation and free code certificate in Readme.md

### ISSUE THREAD

**Issue by SabotageAndi** [Breakthrough/PySceneDetect#321]
Hi
I am the Developer Evangelist from SignPath.

I noticed that there is no mention of us in the readme. 
Could you please add this to your Readme:

```
## Code Signing
This program uses free code signing provided by [SignPath.io](https://signpath.io?utm_source=foundation&utm_medium=github&utm_campaign=PySceneDetect), and a free code signing certificate by the [SignPath Foundation](https://signpath.org?utm_source=foundation&utm_medium=github&utm_campaign=PySceneDetect)

```

Thanks!

**Comment by Breakthrough** [comment]
Hi @SabotageAndi;

Thanks for reaching out, we will definitely add this to the README.md here on Github.  Currently there is a notice on the official download page at [1].  My apologies if the policy has changed since I added it to there, I thought it only needed to be on the main download page.

For my own understanding, would adding the notice on the releases page also be sufficient?

[1] https://github.com/Breakthrough/PySceneDetect/blob/master/docs/download.md

**Comment by Breakthrough** [comment]
Added the text as provided, and also updated the text on the download page to match what you wrote above.  Is there a different `utm_medium` you wish to use for the main website as opposed to Github?

(ref. 2e1000fc0e7a3ebb1169266dbf98135840d8cb20 which appears at https://pyscenedetect.readthedocs.io/en/latest/download/)

**Comment by SabotageAndi** [comment]
Awesome! Thanks!
If you could use `website` as `utm_medium` on the website, that would be great!

**Comment by SabotageAndi** [comment]
> My apologies if the policy has changed since I added it to there, I thought it only needed to be on the main download page.

No problem. I am new at SignPath, so no idea if the policies changed in the past. I just went through the list of projects at the foundation and found some that don't have the mention in the Readme.md on GitHub.
