### ISSUE TITLE
"backend=pyav" about speed

### ISSUE THREAD

**Issue by babyta** [Breakthrough/PySceneDetect#325]
Is it normal that setting backend=pyav is slower than opencv in the latest version of the library?

**Comment by wjs018** [comment]
It is probably going to depend a lot on your specific environment/hardware. For what it is worth, I just analyzed a video using both backends and my results are in the table below. Note that I used both pyav 10.0 (latest) as well as the last pyav 9.X version since there are some major changes between them.
| Backend | FPS Analyzed |
|--------|--------|
| OpenCV | 339.36 |
| PyAV 10 | 334.89 |
| PyAV 9 | 347.42 | 

For reference, here are my package versions:
- python 3.10
- scenedetect 0.6.1
- opencv 4.7.0.72
- pyav 10.0.0/9.2.0
- numpy 1.24.3

**Comment by babyta** [comment]
Thanks, I'll test it later
