### ISSUE TITLE
Hello, can you pass out _frame_scores as a list that can be obtained, so that I can do post-processing on the split results

### ISSUE THREAD

**Issue by babyta** [Breakthrough/PySceneDetect#326]
Hello, can you pass out _frame_scores as a list that can be obtained, so that I can do post-processing on the split results

>  min_length_met = (frame_num - self._last_scene_cut) >= self._min_scene_len
>         if self._frame_score >= self._threshold and min_length_met:
>             self._last_scene_cut = frame_num
>             return [frame_num]

as above
Only split frames are passed out, if you are not satisfied with the result, you cannot add post-processing edits

**Comment by Breakthrough** [comment]
Hi @babyta;

You can obtain the scores for each frame using a [StatsManager](http://scenedetect.com/projects/Manual/en/latest/api/stats_manager.html) when doing scene detection.  Is this what you were looking for?

Thanks!

**Comment by babyta** [comment]
‘’scene_manager.stats_manager._frame_metrics ‘’    works, thank you very much

**Comment by babyta** [comment]
Hello, how can I get the result of this parameter directly?      =====>>  _frame_score

**Comment by Breakthrough** [comment]
Could you elaborate a bit more on your use case @babyta or file a specific feature request for that?  I don't want people to depend on `_frame_score` directly since that is a private API, so we need to come up with a better way.

Eventually I want to refactor the detector API to better support this, but for now we might need to think of a workaround.  If you still need this please file a new issue with an example of how you might use the information so we can best implement it.

**Comment by babyta** [comment]
Solved，data in ‘scene_manager.stats_manager._frame_metrics’
