### ISSUE TITLE
min_scene_len usage of

### ISSUE THREAD

**Issue by babyta** [Breakthrough/PySceneDetect#330]
After testing, it is found that min_scene_len does not post-process the threshold segmentation results. For example, the four scenes are 2.3s, 1.2s, 3s, 2.2s. When min_scene_len=5, the output result will be 2.3+1.2+3=6.5s, 2.2s . But the current result may be like this 5s, 3.7s like this.

**Comment by babyta** [comment]
I looked at the source code and felt that using the content threshold to segment first, and then filtering with duration will get reasonable results. In a video with complex textures, if the _frame_score>_threshold of multiple consecutive frames is possible, the result will become unstable if the strip is split according to _min_scene_len. for example:
The _frame_score of 100-120 frames is 50 greater than _threshold, and the initial duration, such as 15 frames, will be cut to the 100th frame, and if it is set to 30 frames, it will be cut to the 115th stitch, so that the boundary of the frame will change.

**Comment by wjs018** [comment]
I can't claim to fully understand the issue, but if you set `min_scene_len=5`, then that will set it to 5 frames rather than 5 seconds. To set the `min_scene_len` to 5 seconds, you need to append s onto the number (e.g. `min_scene_len="5s"` in python).

Your second point (if I understand correctly) is actually something I have come across before and done some initial thinking about. If I understand, then you are pointing out that there are instances in which a video can have different periods (scenes perhaps) in which a low threshold makes sense, but then other periods in which a high threshold makes sense. The best solution present in pyscenedetect right now is the `detect-adaptive` detector that does try to adapt to the nearby frames and adjust the threshold as it goes. However, there is no perfect algorithm, so we are always open to new approaches.

**Comment by babyta** [comment]
Thank you for your reply. What you said makes sense. At present, I am processing the content threshold and the minimum duration asynchronously. That is to say, the default value is 15, and a post-processing is added to limit the duration.
