### ISSUE TITLE
Ignore time intervals

### ISSUE THREAD

**Issue by yumianhuli1** [Breakthrough/PySceneDetect#374]
Hello！
     Is there an option to ignore time intervals smaller than a certain time period and incorporate that time period into the previous scene? Or in order to keep the api simple, now can only filter according to the judgment conditions, and then use for example -- split_video_ffmpeg?
Thanks

**Comment by wjs018** [comment]
There is the `-m`, `--min-scene-len` option you can give to scenedetect ([documentation here](https://www.scenedetect.com/docs/latest/cli.html#cmdoption-scenedetect-m)). This takes a timecode as an argument and will ignore any detected scene transitions that happen less that that amount of time or number of frames since the previous transition.

For example

```bash
scenedetect -i video.mp4 -m 5s detect-content
```

would ignore any detected scene transitions that happen less than 5 seconds from the previous detected scene transition. So, it would just be part of the scene before it.

**Comment by yumianhuli1** [comment]
> There is the `-m`, `--min-scene-len` option you can give to scenedetect ([documentation here](https://www.scenedetect.com/docs/latest/cli.html#cmdoption-scenedetect-m)). This takes a timecode as an argument and will ignore any detected scene transitions that happen less that that amount of time or number of frames since the previous transition.
> 
> For example
> 
> ```shell
> scenedetect -i video.mp4 -m 5s detect-content
> ```
> 
> would ignore any detected scene transitions that happen less than 5 seconds from the previous detected scene transition. So, it would just be part of the scene before it.

Ok, thank you very much. Could you plz tell me the python call api equivalent to this CLI？

**Comment by wjs018** [comment]
Using the python api, you would set `min_scene_len` per detector when you create it (default is 15 frames, see [here](https://github.com/Breakthrough/PySceneDetect/blob/main/scenedetect/detectors/content_detector.py#L105) for definition in the `__init__` function of the `ContentDetector`).

One difference between the cli and python api is, I believe, the python api expects `min_scene_len` to be an int corresponding to a minimum number of frames. By contrast, using the cli, you can either specify the number of frames or a timecode. If you need to programatically find the framerate of your video, you should be able to access that through a property of the `VideoStream` object. So, let's say you open `video.mp4` using

```python
from scenedetect import open_video

video = open_video("video_file.mp4")  # This returns a VideoStream object
```

you can then access the framerate of the video through `video.framerate`.

@Breakthrough I am just realizing from this conversation how the cli and python api treat `min_scene_len` differently. Is my understanding of this correct? And, if so, should `min_scene_len` be made more flexible for the python api in a future version or set at the `SceneManager` level rather than per detector?

**Comment by Breakthrough** [comment]
Your understanding is correct!  The current API could be updated to use a `FrameTimecode` for detectors.

The idea I have for the long-term 1.0 API would be something where detectors simply generate a set of events (e.g. Event.CUT, Event.START for fade in, Event.END for fade out), and feed those to a SceneManager.  Then, SceneManager could be responsible for actually respecting min_scene_len by dropping CUT events that are too close together when you call `get_scene_list()`.  One benefit of doing this as a post-processing step is the ability to call multiple times with different lengths without needing to run detection again.  This would break how callbacks currently work, but perhaps that is okay as doing this kind of filtering online in a callback is relatively easy (e.g. ignore Event.CUTs that are just too close to the last one).

That being said your suggestion is a good idea and might bring us one step closer to that vision.  It's certainly possible to deprecate `min_scene_len` on detectors, and add a new argument for that purpose to `SceneManager.get_scene_list()`.  One downside of this approach though is it will not work correctly with the `callback` function that `detect_scenes()` takes, so this may need to be an intrinsic property of a given detection run (e.g. passed to `detect_scenes()` or made a property of `SceneManager`) and handled as an online filter.

**Comment by yumianhuli1** [comment]
thanks！close
