### ISSUE TITLE
Group similar scenes together

### ISSUE THREAD

**Issue by yongyongdown** [Breakthrough/PySceneDetect#404]
Hello, thank you for your great program. 

Through split_video_ffmpeg, we confirmed that the scene is split when it changes. 

However, when a scene progresses in the order (a - b - c), if a and c are similar (same camera angle, same person, etc.), is a grouping function possible?

**Comment by wjs018** [comment]
What you are talking about here is sometimes referred to in the literature as shot threading. Basically, some way to identify regions of video between each cut point that are similar in some way. [Here (pdf)](https://openaccess.thecvf.com/content_cvpr_2014/papers/Tapaswi_StoryGraphs_Visualizing_Character_2014_CVPR_paper.pdf) is an example paper that talks about it and provides some other references (paid access) [here](https://doi.org/10.1109/TMM.2008.2008924) and [here](https://doi.org/10.1007/978-3-540-88693-8_12).

In general, I would consider this problem as out of scope for this project (though @Breakthrough is free to disagree) since the focus is really on the detection of the cut points rather than scene comprehension to that extent. I do understand that the line can be blurry a bit as trying to figure out ways to detect difficult scene transitions (fades, dissolves, etc.) or avoid false positives (motion, flashes, edges) can border on more complex scene comprehension.

I haven't wanted or needed to do this kind of threading in the past, so I can't say that I have a good alternative library to point you towards.

**Comment by yongyongdown** [comment]
Thank you very much for your response. Thanks to you, I have learned the keyword "shot threading" for the first time. Although I need more time to understand it fully, it seems to be similar to what I am looking for. I will look into it further.

I had a simpler idea in mind.
If we can determine that scenes are different, then couldn't we also determine that scenes are similar?

If we use a threshold to decide that scenes are different, then I thought that if we join scenes a and c, and the resulting video does not exceed the threshold, we could determine that they are the same (or similar) scenes.

I am curious if this concept is feasible.

**Comment by Breakthrough** [comment]
The new histogram detector would be useful for this, but I agree with @wjs018 that this is probably out of scope for PySceneDetect.  That being said, we can certainly try to add API functionality that would allow this to be developed from the library.

One could calculate the mean histogram for each shot, and then use a post-processing step to group shots based on histogram similarity.  The hash detector might also be useful for this purpose.

This would require exporting the histograms to the StatsManager on each frame, so some thought might need to be done there with respect to buffering.  Currently on each run the StatsManager buffers all metrics until they are saved to disk - we might need to revisit that approach to keep up with the volume of data here.

I'm not sure when these changes could be scheduled for, but am open to any PRs that can make progress on this.
