### ISSUE TITLE
Multiple input files not working as before

### ISSUE THREAD

**Issue by theojk1** [Breakthrough/PySceneDetect#430]
**Description:**

before I was using v0.5.5 and I using the tool with VOB-Files. I call the scenedetect with multiple -i arguments and it concat alle inputs to one large one and run the tool without problems.
now, with v0.6.4 it only process the last input file and not all.

**Command:**

"PySceneDetect-0.6.4\scenedetect.exe" -i "%cd%\VTS_01_1.VOB" -i "%cd%\VTS_01_2.VOB" -i "%cd%\VTS_01_3.VOB" -i "%cd%\VTS_01_4.VOB" -i "%cd%\VTS_01_5.VOB" -i "%cd%\VTS_01_6.VOB"  -o "%cd%\ENC" -m 5s --stats "%cd%\\ENC\Stats.csv" detect-content -t 40 list-scenes 

**Output:**

It only processes the 6600 frames of the last file "%cd%\VTS_01_6.VOB" 

**Environment:**
Windows 10 22h2
No install was used, just the portable windows version

**Media/Files:**
too big to upload

**Workaround**
concat all vob files to one big file and run it with that file.

**Comment by Breakthrough** [comment]
This is being tracked in #430.  I apologize for dropping this feature with the launch of v0.6, however it was difficult to maintain with the state of the codebase at the time.

Is the workaround suitable for your use case?

Supporting something like this reliably isn't easy, since there are various sub-commands that would have to handle shots spanning video boundaries (e.g. split-video).  If PySceneDetect supports this it needs to work correctly with all the subcommands gracefully, which is where the difficulty lies.

**Comment by wjs018** [comment]
I think the correct issue tracking this is #379.

For what it is worth, I used to loop through tons of files all the time, but I only really use the python api. I basically had a python script that found all the files with a specific file extension (`.VOB` in your case) and then detected the scenes for each in turn. The only tricky part that might arise is if scenes are meant to span across two files. That was never true for my use-case though.

**Comment by theojk1** [comment]
Processing each vob file separately is not an option for me. The workaround with the concatenation of all input files to one big file is working for me. If you want to have a feature request: suporting of other input types: AviSynth or just a std-input which can be filled by a pipe by another program, which are designed to handle mutiple vob files.
