### ISSUE TITLE
Issue with stats_file: -s

### ISSUE THREAD

**Issue by coder1508** [Breakthrough/PySceneDetect#52]
scenedetect -i 01.mp4 -s FILE -d content

Getting the same issue: in detect_scenes ['Frame Number'] + ['Timecode'] + stats_file_keys) TypeError: can only concatenate list (not "dict_keys") to list

Could someone let me know how you solved this problem.

In Issue: 34 
https://github.com/Breakthrough/PySceneDetect/issues/34

 it's suggested to use -co but I am agree with comment from @msbrown: I am not looking for -co as that outputs scenes. What I want is a file with the column that denotes the average intensity of the pixel so I can determine the threshold.

**Comment by Breakthrough** [comment]
Thank you for bringing this to my attention.

I hope to address this with the release of v0.5, as the stats file system will be entirely reworked with a dedicated StatsManager class, which should prevent a lot of these TypeError issues that are cropping up.  It should be out by the end of the month, you can track the progress or suggest any changes here: #57 

Thanks for the report.

**Comment by Breakthrough** [comment]
This is now fixed in v0.5, which now has significantly better error reporting for stats file issues.  v0.5 is still under development, and can be tested by checking out the v0.5-dev branch of PySceneDetect.

I have marked this issue as completed for now, but will leave it open until the relevant changes have been merged with the master branch.  Thank you again.
