### ISSUE TITLE
Possible solution for update concerning scenes extracted using -o not conforming with scene list given using -l

### ISSUE THREAD

**Issue by GregorWenzel** [Breakthrough/PySceneDetect#63]
When I extract an mp4, I get a correct list of scenes from stdout (using -l option). But, the generated split scenes using option -o do not conform with that list. Some of the clips contain more than one of the detected scenes.

Reproducing this issue with the generated timecodes and ffmpeg, I found that I get the same erroneous scene clips using "-ss [start_timecode] -t [end_timecode]". Instead, the correct usage is "-ss [start_timecode] **-to** [end_timecode]", at least with the mp4 files I use as input.

Please check if an update to PySceneDetect is necessary or if I am using it incorrectly.

**Comment by Breakthrough** [comment]
Hi @GregorWenzel;

When you say the split scenes, do you mean the output .MKV files?  (PySceneDetect uses mkvmerge not ffmpeg, but the next version may use both)  Also, are you just copying the codec when using ffmpeg, or re-encoding?  This may be due to keyframe alignment issues.

The mkvmerge command takes a list of timecodes in a single CLI argument, as opposed to ffmepg which requires one call per scene to output.

Would you be able to test splitting the files using the scene list and mkvmerge to see if the same behaviour occurs?  The command to use would be:

    mkvmerge -o [OUTPUT_PATH] --split timecodes:[TC_LIST] [INPUT_PATH]

For example:

    mkvmerge -o output.mkv --split timecodes:00:00:30.290,00:01:20.000,00:05:00.000 input_video.mp4

**Comment by Breakthrough** [comment]
This has been implemented in v0.5 and is awaiting official release (you can pull the v0.5-dev branch and test the new version if you would like to provide some pre-release feedback).  The overall command to split videos quickly (i.e. no reencoding) is now (using the detect-content detector):

    scenedetect --input video.mp4 detect-content split-video

    scenedetect --input video.mp4 detect-content split-video

This is equivalent to specifying `ffmpeg -c:v copy -c:a copy` for each scene.  Likewise, to improve precision, one can supply the `-p` option to use `libx264` as the video encoder:

    scenedetect --input video.mp4 detect-content split-video -p

Furthermore, the codecs passed to ffmpeg can be set manually via `-c`, for example:

    scenedetect --input video.mp4 detect-content split-video -c "-c:v libx264 -c:a aac"

Lastly, there is still support for splitting the video using `mkvmerge`, but now `ffmpeg` will be the default tool used, if available.  Mkvmerge can be chosen explicitly via: the `-m` option:

    scenedetect --input video.mp4 detect-content split-video -m
