### ISSUE TITLE
scenedetect process video fail

### ISSUE THREAD

**Issue by aelous** [Breakthrough/PySceneDetect#75]
**Bug/Issue Description:**
GStreamer Plugin: Embedded video playback halted; module decodebin20 reported: Your GStreamer installation is missing a plug-in.
$ scenedetect -i test.flv
[PySceneDetect] Detecting scenes (threshold mode)...
GStreamer Plugin: Embedded video playback halted; module decodebin20 reported: Your GStreamer installation is missing a plug-in.
[PySceneDetect] Parsing video test.flv...
[PySceneDetect] Video Resolution / Framerate: 0 x 0 / 0.000 FPS
Verify that the above parameters are correct (especially framerate, use --force-fps to correct if required).
[PySceneDetect] Processing complete, found 0 scenes in video.
[PySceneDetect] Processed 0 frames in 0.0 secs (avg. 0.0 FPS).

**Required Information:**

PySceneDetect v0.3.4
**Computing Environment:**
 - OS: centos7
 - Python Version: 2.7
 - OpenCV Version:2.4

**Comment by aelous** [comment]
I just install gstreamer, but some dependencies are not all installed.
fixed by `yum install ffmpeg ffmpeg-devel gstreamer-ffmpeg gstreamer-plugins-* -y `

thx~

**Comment by Breakthrough** [comment]
Ideally I would like to be able to detect this behaviour at runtime, and display the appropriate error message.

This is only currently done on Windows, by assuming if opening the VideoCapture fails, and there is no opencv_*ffmpeg.dll file in %PATH%, then the ffmpeg dependency is missing.  This only works for official builds of OpenCV, however, as you found out, some Linux builds (and thus, presumably, Windows as well) substitute gstreamer.

The difficulty with addressing this is I can't really see a way of solving it that's not specific to a particular operating system or version of OpenCV.  On Windows it's a bit easier because I could just add an additional check for the gstreamer DLL once I find out what the appropriate name is, but I'm not sure how to approach this on Linux.

I could check for the appropriate `lib*.*`  files in `$PATH`, but I'm not sure if this approach works on all Linux distros, or OS X.  I'll mark this as community feedback requested for now, as any input on the matter would be appreciated.

One last option would just be to include a very small but valid video in the PySceneDetect source code, and if opening it fails, display an error message indicating that OpenCV has not been installed correctly.  Any feedback/opinions on what an end user's expectation of behaviour in this case would be is greatly appreciated.

Thanks for the report @aelous, really appreciate you sharing the solution as well.

**Comment by Breakthrough** [comment]
Closing issue to cleanup backlog.  Feel free to re-open should it reoccur, or if anyone has any suggestions on how to appropriately handle this failure case.
