### ISSUE TITLE
some feature that i like in next update

### ISSUE THREAD

**Issue by kucingkembar** [Breakthrough/PySceneDetect#92]
hi, sorry for my bad english,
i using this software almost daily, 
i using the "exe" that you provide,
to be honest this software is great,
1.but if the file above 1 gb, the process time is quite long, sometime over 3 hours for 4gb+,
can you do something about that?
2.the progress bar in cmd is not available, i dont know if the process is under 10% or over  95%, that i know the processor is busy in task manager
3.if error happen, please make log, why it error, 
thanks for reading

**Comment by Breakthrough** [comment]
Hi @kucingkembar;

 1. I'm planning on addressing this with a new project called [SceneStats](https://github.com/Breakthrough/SceneStats).

 2. Do you have tqdm installed (e.g. `pip install tqdm`)?

 3. Logging has been implemented as of PySceneDetect v0.5, you can add `-v` or `-v debug` to see additional information when running PySceneDetect.  Additionally, a logfile can be specified with `--logfile output_log.txt`.

Thanks!

**Comment by kucingkembar** [comment]
sorry for my late reply, i though you will not answer this page,
1. i read it in another page, you will support GPU processing in SceneStats, i can wait until that release, but i will give you a warning, once i try split using ffmpeg with "-c:v h264_nvenc" code it really fast(5x fast), but the cut is not precise, i hope aware of this,

2.i using exe version, i assume it not support "pip install tqdm", just python installation makes me crazy

3. oh, you have logging system, sorry i not command line user,

4. sorry if it about a request, can this software port it to android?

thanks for the reply

**Comment by Breakthrough** [comment]
Hi @kucingkembar.

1. Thanks for letting me know, will investigate.

2. Sorry, just FYI the .exe version is not going to be supported anymore (see #102) to simplify distribution of PySceneDetect.

What troubles do you have with installing Python?  Once it is installed you should be able to run `pip install opencv` and `pip install scenedetect`, and everything should just work.

3. Sorry yes, if you're using the .exe the last version of that was v0.4.  v0.5 is the new version, but is only released via `pip` now.

4. That may be possible for SceneStats since it's written in C++, but currently, porting PySceneDetect to run natively on Android may be a non-trivial task.

Thanks!
